server.servlet.context-path: "/v1"
server.port: 8088
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "auditevents,beans,caches,conditions,configprops,env,health,heapdump,trrptrace,info,integrationgraph,jolokia,logfile,loggers,liquibase,metrics,mappings,prometheus,scheduledtasks,sessions,startup,threaddump"
spring:
  application.name: "kafkaBinderDemo"

  cloud.stream:
    kafka.binder.brokers: "localhost"
    kafka.bindings:
      testInput.consumer.autoCommitOnError: true
      # for some reason we can't put this in the common library, where the producer lives
      testOutput.producer.configuration.key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
    bindings:
      testOutput:
        producer.partitionCount: 2
      testInput:
        group: "demoGroup"



