server.servlet.context-path: "/v1"
server.port: 8088

management.endpoints.enabled-by-default: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "shutdown"
spring:
  cloud.stream:
    kafka.binder.brokers: "localhost"
    kafka.bindings:
      # for some reason we can't put this in the common library, where the producer lives
      testOutput.producer.configuration.key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
    bindings:
      testInput:
        group: "demoGroup"
      testOutput:
        producer.partitionCount: 2



