server.servlet.context-path: "/v1"
server.port: 8088

management.endpoints.enabled-by-default: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: "env,configprops,health,httptrace,loggers,metrics,mappings,prometheus"
        exclude: "shutdown"
spring:
  application.name: "kafkaBinderDemo"
  cloud.stream:
    defaultBinder: scl
    binders:
      scl:
        type: kafka
        environment.spring.cloud.stream:
          kafka.binder.brokers: "localhost:9092"
      scl1:
        type: kafka
        environment.spring.cloud.stream:
          kafka.binder.brokers: "localhost:9092"
    bindings:
      testOutput:
        destination: "testOutputDev"
        binder: scl1
      testInput:
        destination: "testInputDev"
        group: "demoGroup"
    kafka.binder.autoAddPartitions: true


