server.servlet.context-path: "/v1"
server.port: 8088
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "auditevents,beans,caches,conditions,configprops,env,health,heapdump,trrptrace,info,integrationgraph,jolokia,logfile,loggers,liquibase,metrics,mappings,prometheus,scheduledtasks,sessions,startup,threaddump"
spring:
  application.name: "kafkaBinderDemo"

  cloud.stream:
    kafka.binder.brokers: "localhost"
    kafka.bindings:
      testInput-in-0.consumer.autoCommitOnError: true
    bindings:
      testInput-in-0:
        destination: testInput
        group: "demoGroup"

  cloud:
    function:
      definition: testInput